### ISSUE TITLE
PostScript error: undefined in findfont

### ISSUE THREAD

**Issue by paul-jh** [mgieseki/dvisvgm#132]
dvisvgm fails to compile this

test.tex:
```
\documentclass{minimal}
\usepackage{pstricks}
\begin{document}
 \begin{pspicture}[showgrid](0,0)(3,3)
 \psline(0,0)(2,2)
 \end{pspicture}        
\end{document}
```

Calling
`latex test.tex; dvisvgm test.dvi`
yields:

```
pre-processing DVI file (format version 2)
processing page 1
  PostScript error: undefined in findfont
  Operand stack:
      0.0  0.0  85.3582  85.3582  0.0  0.0  28.4527  28.4527  1  10  --nostringval--  8.0  NimbusSanL-Regu
```

(btw.: Without "[showgrid]" the call is successful. The "NimbusSanL-Regu" may rely on this.)

A dist-upgrade of my xubuntu (now: ghostscript 9.27 , dvisvgm 2.6.3) did not "solve" this.
This is presumably not a dvisvgm error, but might be behaviour caused by some "incompatibilities" with ghostscript?

**Comment by mgieseki** [comment]
> This is presumably not a dvisvgm error, but might be behaviour caused by some "incompatibilities" with ghostscript?

Yes, this is indeed a bug in Ghostscript 9.27 that was fixed in 9.50. Unfortunately, the old dvisvgm 2.6.3 does not work together with GS 9.50 due to incompatible changes in the latest GS releases. Therefore, you need to upgrade both Ghostcript and dvisvgm to more recent versions in order to get rid of the error message.

**Comment by paul-jh** [comment]
Thanks!
I compile dvisvgm from source (2.9.1) and downloaded ghostscript (9.52) binary.
test.dvi is still not compiled. The error message stays the same. 

xubuntu 20.04 will be released in some weeks - i hope, it comes with a ghostscript setup, 
that works for me (...)

**Comment by mgieseki** [comment]
Does your dvisvgm really use GS 9.52? You could check this with `dvisvgm -V1`. I can't reproduce the issue with GS 9.52 here.

**Comment by paul-jh** [comment]
I'm sorry. You are right. Thanks a lot!

**Comment by mgieseki** [comment]
You're welcome. Hope you were able to solve the issue.
