### ISSUE TITLE
Issues building on Ubuntu

### ISSUE THREAD

**Issue by bernd-wechner** [mgieseki/dvisvgm#88]
I just built this successfully on Ubuntu, but ran into these two problems that needed fixing:

1.  autogen.sh/configure failed to install or warn of the need to install libkpathsea-dev so compile bombed. Fixed by running `sudo apt install libkpathsea-dev`

2. Same deal with `sudo apt install libpotrace-dev`.  Did it manually only because make bombed.

3. libpotrace.so is not linked to causing the link to bomb. I fixed by manually running:

`g++ -std=gnu++11 -Wall -Wnon-virtual-dtor -Wno-mismatched-tags -I../libs/clipper -I../libs/variant/include -I../libs/xxHash -I/usr/include/freetype2 -I../libs/brotli/include -I../libs/woff2/include -g -O2 -o dvisvgm dvisvgm.o  libdvisvgm.a ../libs/clipper/libclipper.a ../libs/xxHash/libxxhash.a /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/x86_64-linux-gnu/libpotrace.so ../libs/ff-woff/libfontforge.a ../libs/woff2/libwoff2.a ../libs/brotli/libbrotli.a -lz -ldl -lkpathsea`

which was lacking `/usr/lib/x86_64-linux-gnu/libpotrace.so`.

I'd fix the configs but am totally green on autoconfig.sh and configure right now and will run with my current build which reports:

```
$ ./dvisvgm --version
dvisvgm 2.4
```

and is what I need to get TexMath in LibreOffice to support xelatex because Ubuntu has a cruddy old dvisvgm build:

```
$ dvisvgm --version
dvisvgm (TeX Live) 1.9.2
```

which TexMath doesn't like. I'm hoping someone real familiar with the autogen system can fix these three glitches so an Ubuntu user can just clone the repo and build without these time consuming hitches.

**Comment by mgieseki** [comment]
The script `autogen.sh` is just supposed to set up the autotools environment by running `aclocal`, `autoconf`, `autoheader`, and `automake`. It is not designed to manage any missing build dependencies . These must be resolved in advance since the mentioned autotools are dependencies of dvisvgm themselves (among many others). Because of the different package management systems and various naming schemes across operating systems, there is no easy way to provide a script that handles all of them. 
The correct way to fix your issue would be to update the Ubuntu package that provides the ancient dvisvgm. Maybe you should ask the Ubuntu maintainers to provide a more recent version.

**Comment by bernd-wechner** [comment]
Thanks. That explained 1 and 2 it doesn't fix 3. Which seems a bug in the configs.

That said, autogen.sh or configure (can't recall which) did, I feel sure, advise me on other missing packages when it ran. But I was following the README.md under "Building dvisvgm from source" and it went pretty smoothly and perfectly bar those three issues. 

Seems to me, that yes, there is a (lamentable to my mind) abundant diversity of Linux distros and package management systems, but one can do a lot worse than supporting the most popular one IMHO. If I make/find time I'll try and get my head around the autoconf schema as it is very widespread and remains a (personal) mystery ... ;-). Then I might find it easier to patch something to fix that third issue and post a PR. 

But yes, Ubuntu should update and I'll check with that too (quite poor form that it's so out of date).
